//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartment
    {
        public string Appartment_Id { get; set; }
        public string AppartmentNumber { get; set; }
        public string Size { get; set; }
        public string Building_Id { get; set; }
        public bool Status { get; set; }
        public string Tenant_Id { get; set; }
        public int Rent { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual Building Building { get; set; }
    }
}
